version: "3"

services:
         
        flask:
                build: ./flask
                container_name: flask
                volumes:
                        - ./flask:/home/emm7494/flask
                env_file:
                         ./flask/.flaskenv
                env_file:
                         ./flask/.env
                # depends_on:
                #         - nginx

        nginx:
                build: ./nginx
                container_name: nginx
                volumes:
                        - ./flask/app/static:/var/www/flask/static
                        - ./flask/app/html:/var/www/flask/html
                ports:
                        - "80:80"
                # depends_on:
                #         - flask

       